"""Начальная миграция для модели Movie."""

# Generated by Django 4.2.25 on 2025-11-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция, создающая модель Movie."""

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="movies/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "trailer_link",
                    models.URLField(
                        max_length=500,
                        verbose_name="Ссылка на трейлер",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Длительность в минутах",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
                "ordering": ["title"],
            },
        ),
    ]
